### ISSUE TITLE
Lookit me abusing the isssues section :P

### ISSUE THREAD

**Issue by crimeedge** [NetDenizen/Test-Renpy-Project#1]
Nice work! I didn't know how to import your project into renpy on my end after cloning, as I'm dumb. You think you can get Mal to synch with the github here or on some other repo?

**Comment by NetDenizen** [comment]
Thanks, and hello! I need to start paying attention to this.

First thing: You should be able to just dump the test_project_1 directory to the normal directory the Ren'Py launcher stores projects.

Second: Mal should be able to fork this repository, no problem, if that's what you mean.

This is really just intended as a testbed, anyway.
